URL: "http://192.168.3.183:14010/iot/login"
PASSWORD: '000000'
ADMIN: "whrwyy_test"
ADMINNAME: "test_name"
CHIPID: "50703"
alarmId: ""
PHONE: '18062427385'
PLATENUMBER: "湖北50703"
VIN: "50703"
GZAPP: ""
DEVICEAPP: ""
RODNUM: "111555"
BASENUM: "111555"