URL: "http://192.168.3.54:14010/iot/home"
PASSWORD: '000000'
ADMIN: "system"
ADMINNAME: "系统管理员"
CHIPID: "50703"
alarmId: ""
PHONE: '18062427385'
PLATENUMBER: "湖北50703"
VIN: "50703"
GZAPP: ""
DEVICEAPP: ""
RODNUM: "111555"
BASENUM: "111555"